### ISSUE TITLE
Please verify that if you'd use the code as the following if (uniform_location) which conversion it'd use, the bool one or the s32 one

### ISSUE THREAD

**Issue by RisingLiberty** [Dyronix/Rex#27]
Please verify that if you'd use the code as the following if (uniform_location) which conversion it'd use, the bool one or the s32 one

_Originally posted by @RisingLiberty in https://github.com/Dyronix/Rex/pull/19#discussion_r1110117820_

**Comment by Dyronix** [comment]
The following function is use =>

    //-------------------------------------------------------------------------
    explicit operator bool() const
    {
      return m_location != -1;
    }
